# Generated by Django 4.2.3 on 2023-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsl_api', '0002_lslscript_email_lslscript_share_lslscript_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lslscript',
            name='execution_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lslscript',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
