# Generated by Django 4.2.3 on 2023-07-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsl_api', '0003_lslscript_execution_id_lslscript_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lslscript',
            old_name='lsl_script',
            new_name='script',
        ),
    ]
