# Generated by Django 4.2.1 on 2023-07-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsl_api', '0004_rename_lsl_script_lslscript_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='lslscript',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lslscript',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lslscript',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lslscript',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lslscript',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
