# Generated by Django 4.2.3 on 2023-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsl_api', '0005_lslscript_end_lslscript_name_lslscript_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lslscript',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
