# Generated by Django 4.2.3 on 2023-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsl_api', '0006_lslscript_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LassoResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(max_length=100)),
                ('abstraction_id', models.CharField(max_length=100)),
                ('action_id', models.CharField(max_length=100)),
                ('arena_id', models.CharField(max_length=100)),
            ],
        ),
    ]
